//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCharge
    {
        public string msisdn { get; set; }
        public string REGION { get; set; }
        public Nullable<float> JAWWAL_MAIN_CHARGE { get; set; }
        public Nullable<float> fraction { get; set; }
        public Nullable<float> WATANIYA_MAIN_CHARGE { get; set; }
        public Nullable<float> ONNET_TERMINATING { get; set; }
        public Nullable<float> ISRAEL_MAIN_CHARGE { get; set; }
        public int PACKAGE_Code { get; set; }
    }
}
